# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
wally = "upliftgames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.6.1"
selene = "kampfkarren/selene@0.29.0"
luau-lsp = "johnnymorganz/luau-lsp@1.60.0"
stylua = "johnnymorganz/stylua@2.3.1"
pesde = "pesde-pkg/pesde@0.7.2+registry.0.2.3"
zune = "Scythe-Technology/zune@0.5.3"
